config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  get 'users/show'
  get 'users/index'
  root 'static_pages#home'
  get :about,        to: 'static_pages#about'
  get :use_of_terms, to: 'static_pages#terms'
  get :signup,       to: 'users#new'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :cosmes
  get    :login,     to: 'sessions#new'
  post   :login,     to: 'sessions#create'
  delete :logout,    to: 'sessions#destroy'
  resources :relationships, only: [:create, :destroy]
  get :favorites, to: 'favorites#index'
  post   "favorites/:cosme_id/create"  => "favorites#create"
  delete "favorites/:cosme_id/destroy" => "favorites#destroy"
  resources :comments, only: [:create, :destroy]
  resources :notifications, only: :index
  get :lists, to: 'lists#index'
  post   "lists/:cosme_id/create"  => "lists#create"
  delete "lists/:list_id/destroy" => "lists#destroy"
  resources :logs, only: [:create, :destroy]
end

app/models/cosme.rb
class Cosme < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :lists, dependent: :destroy
  has_many :logs, dependent: :destroy
  has_many :makers, dependent: :destroy
  accepts_nested_attributes_for :makers
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :name, presence: true, length: { maximum: 30 }
  validates :description, length: { maximum: 140 }
  validates :tips, length: { maximum: 50 }
  validates :popularity,
            :numericality => {
              :only_interger => true,
              :greater_than_or_equal_to => 1,
              :less_than_or_equal_to => 5
            },
            allow_nil: true
  validate  :picture_size

  # コスメに付属するコメントのフィードを作成
  def feed_comment(cosme_id)
    Comment.where("cosme_id = ?", cosme_id)
  end

  def feed_log(cosme_id)
    Log.where("cosme_id = ?", cosme_id)
  end

  private

    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "：5MBより大きい画像はアップロードできません。")
      end
    end
end

app/controllers/cosmes_controller.rb
class CosmesController < ApplicationController
  before_action :logged_in_user
  before_action :correct_user, only: [:edit, :update]

  def new
    @cosme = Cosme.new
    @cosme.makers.build
  end

  def index
    @log = Log.new
     # CSV出力時のファイル名指定
    respond_to do |format|
      format.html
      format.csv {
        send_data render_to_string,
                  filename: "みんなの投稿一覧_#{Time.current.strftime('%Y%m%d_%H%M')}.csv"
      }
    end
  end

  def show
    @cosme = Cosme.find(params[:id])
    @comment = Comment.new
    @log = Log.new
  end

  def create
    @cosme = current_user.cosmes.build(cosme_params)
    if @cosme.save
      flash[:success] = "コスメが登録されました！"
      Log.create(cosme_id: @cosme.id, content: @cosme.cosme_memo)
      redirect_to cosme_path(@cosme)
    else
      render 'cosmes/new'
    end
  end

  def edit
    @cosme = Cosme.find(params[:id])
  end

  def update
    @cosme = Cosme.find(params[:id])
    if @cosme.update_attributes(cosme_params)
      flash[:success] = "コスメ情報が更新されました！"
      redirect_to @cosme
    else
      render 'edit'
    end
  end

  def destroy
    @cosme = Cosme.find(params[:id])
    if current_user.admin? || current_user?(@cosme.user)
      @cosme.destroy
      flash[:success] = "コスメが削除されました"
      redirect_to request.referrer == user_url(@cosme.user) ? user_url(@cosme.user) : root_url
    else
      flash[:danger] = "他人のコスメは削除できません"
      redirect_to root_url
    end
  end

  private

    def cosme_params
      params.require(:cosme).permit(:name, :description, :tips,
                                    :reference, :popularity, :cosme_memo, :picture,
                                     makers_attributes: [:id, :name, :genre])
    end

    def correct_user
      @cosme = current_user.cosmes.find_by(id: params[:id])
      redirect_to root_url if @cosme.nil?
    end
end

app/helpers/cosmes_helper.rb
module CosmesHelper
end

app/views/cosmes/_cosme.html.erb
<% @cosme = cosme %>

<li id="cosme-<%= cosme.id %>">
  <%= link_to gravatar_for(cosme.user, size: 50), cosme.user %>
  <span class="name"><%= link_to cosme.name, cosme_path(cosme) %></span>
  <span>
    <%= link_to((image_tag cosme.picture.thumb200.url), cosme_path(cosme.id), class: 'cosme-picture') if cosme.picture.url.present? %>
  </span>
  <%= render 'users/favorite_form' %>
  <%= render 'users/list_form' %>
  <span class="description"><%= cosme.description %></span><br>
  <div class="cosme-user">by <%= link_to cosme.user.name, user_path(cosme.user) %></div>
    <div class="cosme-maker">
      <p class="title-maker-mini">【メーカー】</p>
      <% cosme.makers.each_with_index do |ing, i| %>
        <% if ing.name.present? %>
          <%= "｜" unless i == 0 %><%= ing.name %>: <%= ing.genre %>
        <% end %>
      <% end %>
    </div>
  <span class="cosme_times">感想の数：<%= cosme.logs.count %>回　</span>
  <span class="popularity">人気度：<%= cosme.popularity %></span><br>
  <span class="reference"><%= link_to "詳細", cosme.reference, target: :_blank %></span>
   <% if current_user == cosme.user %>
    <%= render "logs/new_form_mini" %>
  <% end %>
  <span class="timestamp">
    <%= time_ago_in_words(cosme.created_at) %>前に投稿
  </span>
  <% if current_user.admin? || (current_user == cosme.user) %>
    <%= link_to "削除", cosme_path(cosme), method: :delete,
                       data: { confirm: "本当に削除しますか？" } %>
  <% end %>
</li>

app/views/cosmes/_cosme_form.html.erb
<%= form_with model: @cosme, local: true do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <span class="picture">
    <%= f.label :picture %><span class="input-unneed">※任意</span>
    <%= f.file_field :picture, accept: 'image/jpeg,image/png', class: 'form-control', id: 'cosme_picture' %>
  </span>
  <div class = 'form-group'>
    <%= f.label :name %><span class="input-need">※必須</span>
    <%= f.text_field :name, class: 'form-control', id: 'cosme_name' %>
  </div>
  <div class = 'form-group'>
    <%= f.label :description %><span class="input-unneed">※任意</span>
    <%= f.text_field :description, size: "60x4", class: 'form-control', id: 'cosme_description' %>
  </div>
  <%= f.fields_for :makers do |i| %>
    <div class="row">
      <div class="col-md-9">
        <div class = 'form-group'>
          <%= i.label :name %><span class="input-unneed">※任意</span>
          <%= i.text_field :name, class: 'form-control maker_name' %>
        </div>
      </div>
      <div class="col-md-3">
        <div class = 'form-group'>
          <%= i.label :genre %><span class="input-unneed">※任意</span>
          <%= i.text_field :genre, class: 'form-control maker_genre' %>
        </div>
      </div>
    </div>
  <% end %>
  <%= render partial: "maker_form", locals: {f: f} %>
  <%= render partial: "maker_form", locals: {f: f} %>
  <div class = 'form-group'>
    <%= f.label :tips %><span class="input-unneed">※任意</span>
    <%= f.text_field :tips, size: "30x4", class: 'form-control', id: 'cosme_tips' %>
  </div>
  <div class = 'form-group'>
    <%= f.label :reference %><span class="input-unneed">※任意</span>
    <%= f.text_field :reference, class: 'form-control', id: 'cosme_reference' %>
  </div>
  <div class = 'form-group'>
    <%= f.label :popularity %> [1~5]<span class="input-unneed">※任意</span>
    <%= f.text_field :popularity, class: 'form-control', id: 'cosme_popularity' %>
  </div>
  <div class = 'form-group'>
    <%= f.label :cosme_memo %><span class="input-unneed">※任意</span>
    <%= f.text_field :cosme_memo, class: 'form-control', id: 'cosme_cosme_memo' %>
  </div>
  <%= f.submit nil, class: 'btn btn-primary' %>

  <script type="text/javascript">
  $('#cosme_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('アップロードできる写真の最大サイズは5MBです。5MB以下の画像を選択してください');
    }
  });
</script>
<% end %>

app/views/cosmes/_maker_form.html.erb
<%= f.fields_for :makers do |i| %>
  <div class="row">
    <div class="col-md-9">
      <div class = 'form-group'>
        <%= i.text_field :name, class: 'form-control maker_name' %>
      </div>
    </div>
    <div class="col-md-3">
      <div class = 'form-group'>
        <%= i.text_field :genre, class: 'form-control maker_genre' %>
      </div>
    </div>
  </div>
<% end %>

app/views/cosmes/edit.html.erb
<% provide(:title, "コスメ情報の編集") %>
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@cosme) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
         <span class="picture">
          <%= f.label :picture %><span class="input-unneed">※任意</span>
          <%= f.file_field :picture, accept: 'image/jpeg,image/png', class: 'form-control', id: 'cosme-picture' %>
          <%= image_tag(@cosme.picture.thumb400.url) if @cosme.picture.url.present? %>
          <p></p>
        </span>
        <p></p>
        <div class = 'form-group'>
          <%= f.label :name %><span class="input-need">※必須</span>
          <%= f.text_field :name, class: 'form-control', id: 'cosme_name' %>
        </div>
        <div class = 'form-group'>
          <%= f.label :description %><span class="input-unneed">※任意</span>
          <%= f.text_field :description, size: "60x4", class: 'form-control', id: 'cosme_description' %>
        </div>
        <div class="row">
          <div class="col-md-9">
            <p class="title-maker-name">メーカー（複数可）<span class="input-unneed">※任意</span></p>
          </div>
          <div class="col-md-3">
            <p class="title-maker-genre">ジャンル<span class="input-unneed">※任意</span></p>
          </div>
        </div>
        <%= f.fields_for :makers do |i| %>
          <div class="row">
            <div class="col-md-9">
              <div class = 'form-group'>
                <%= i.text_field :name, class: 'form-control maker_name' %>
              </div>
            </div>
            <div class="col-md-3">
              <div class = 'form-group'>
                <%= i.text_field :genre, class: 'form-control maker_genre' %>
              </div>
            </div>
          </div>
        <% end %>
        <div class = 'form-group'>
          <%= f.label :tips %><span class="input-unneed">※任意</span>
          <%= f.text_field :tips, size: "30x4", class: 'form-control', id: 'cosme_tips' %>
        </div>
        <div class = 'form-group'>
          <%= f.label :reference %><span class="input-unneed">※任意</span>
          <%= f.text_field :reference, class: 'form-control', id: 'cosme_reference' %>
        </div>
        <div class = 'form-group'>
          <%= f.label :popularity %> [1~5]<span class="input-unneed">※任意</span>
          <%= f.text_field :popularity, class: 'form-control', id: 'cosme_popularity' %>
        </div>
        <%= f.submit "更新する", class: "btn btn-primary" %>
        <p></p>
        <%= link_to "コスメを削除する", cosme_path(@cosme), method: :delete,
                             data: { confirm: "本当にこのコスメを削除してよろしいですか？" } %>
      <% end %>
    </div>
  </div>
</div>

app/views/cosmes/index.html.erb
<% provide(:title, 'コスメ一覧') %>
<div id="fh5co-portfolio">
  <div class="container">
    <% if @search_word.present? %>
      <h3>”<%= @search_word %>”の検索結果：<%= @cosmes.count %>件</h3>
    <% else %>
      <h3>コスメ一覧</h3>
    <% end %>
    <ul class="cosmes">
      <%= render @cosmes %>
    </ul>
    <%= will_paginate %>
  </div>
</div>

app/views/cosmes/new.html.erb
<% provide(:title, "コスメ登録") %>
<div class="container">
  <h1>コスメ登録</h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= render 'cosmes/cosme_form' %>
    </div>
  </div>
</div>

app/views/cosmes/show.html.erb
<% provide(:title, "#{@cosme.name}") %>
<% @comments  = @cosme.feed_comment(@cosme.id) %>
<% @logs  = @cosme.feed_log(@cosme.id) %>
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <span class="picture">
        <%= link_to((image_tag @cosme.picture.thumb400.url), cosme_path(@cosme.id), class: 'cosme-picture') if @cosme.picture.url.present? %>
      </span>
      <%= render 'users/favorite_form' %>
      <%= render 'users/list_form' %>
    </div>
    <div class="col-md-8">
      <h2 class="cosme-name"><%= @cosme.name %></h2>
      <div class="change-cosme">
        <% if current_user == @cosme.user %>
          <%= link_to "編集", edit_cosme_path(@cosme), class: 'edit-cosme' %>
        <% end %>
        <% if current_user.admin? || (current_user == @cosme.user) %>
          <%= link_to "削除", cosme_path(@cosme), method: :delete, class: 'delete-cosme',
                                         data: { confirm: "本当に削除しますか？" } %>
        <% end %>
      </div>
      <h4 class="cosme-description">説明：<%= @cosme.description %></h4>
      <h4 class="cosme-reference">参照用URL：<%= link_to "#{@cosme.reference}", @cosme.reference, target: "_blank" %></h4>
      <div class="makers">
          <h5 class="title-makers">メーカー</h5>
          <div class="row">
            <div class="col-md-8">
              <table class="maker">
                <% @cosme.makers.each do |i| %>
                  <% if i.name.present? %>
                    <tr>
                      <td><%= i.name %></td>
                      <td><%= i.genre %></td>
                    </tr>
                  <% end %>
                <% end %>
              </table>
            </div>
          </div>
        </div>
      <div class="tips">
        <h5 class="title-tips">コツ・ポイント</h5>
        <h5><%= @cosme.tips %></h5>
      </div>
      <div class="show-cosme-other-info">
        <div class="cosme-info">
          <h5>人気度：</h5><h4><%= @cosme.popularity %></h4>
        </div>
      </div>
      <% if current_user == @cosme.user %>
          <div class="log">
            <%= render "logs/feed_logs" %>
            <%= render "logs/new" %>
          </div>
      <% end %>
      <div class="comment">
        <%= render "comments/feed_comments" %>
        <%= render "comments/new" %>
      </div>
    </div>
  </div>
</div>